services:
  - type: web
    name: group-conscience-voting
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
